spring:
  config.activate.on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/user_data?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate.ddl-auto: update

logging.level.root: DEBUG

springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
