spring:
  config.activate.on-profile: dev

  datasource:
    url: jdbc:mysql://${DB_HOST:10.210.40.40}:${DB_PORT:3306}/${DB_NAME:user_data}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:kyc_uat}
    password: ${DB_PASSWORD:CHANGE_ME}
  jpa:
    show-sql: false
    hibernate.ddl-auto: update

  springdoc:
    api-docs.enabled: true
    swagger-ui.enabled: true
